"""Generate forge/1.19.2/tmp-check.gradle with one JavaExec task per *Check.java harness."""
import pathlib, re

root = pathlib.Path(r"C:\Users\skps9\Documents\Code_Project\super_minecraft_AI_player\forge\1.19.2\src\test\java")
entries = []
for f in sorted(root.rglob("*Check.java")):
    txt = f.read_text(encoding="utf-8", errors="replace")
    m = re.search(r"^package\s+([\w.]+);", txt, re.M)
    if not m:
        continue
    pkg = m.group(1)
    cls = f.stem
    task = "run" + cls
    entries.append((task, f"{pkg}.{cls}"))

lines = [
    "// AUTO-GENERATED by research/gen_tmp_check.py - one JavaExec per *Check harness",
    "gradle.projectsEvaluated {",
    "    gradle.rootProject.allprojects { p ->",
    "        if (!p.plugins.hasPlugin('java')) return",
    "        def harnesses = [",
]
for task, fqcn in entries:
    lines.append(f"            '{task}': '{fqcn}',")
lines += [
    "        ]",
    "        harnesses.each { e ->",
    "            p.tasks.register(e.key, JavaExec) {",
    "                it.group = 'verification'",
    "                it.classpath = p.sourceSets.test.runtimeClasspath",
    "                it.mainClass = e.value",
    "                it.jvmArgs '-ea'",
    "            }",
    "        }",
    "    }",
    "}",
]
out = pathlib.Path(r"C:\Users\skps9\Documents\Code_Project\super_minecraft_AI_player\forge\1.19.2\tmp-check.gradle")
out.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"{len(entries)} harnesses")
print(" ".join(t for t, _ in entries))
